
from tkinter import *
root = Tk() 
frame = Frame(root) 
frame.pack() 

#master = Tk() 
Label(root, text='First Name').grid(row=0) 
Label(root, text='Last Name').grid(row=1) 
e1 = Entry(master) 
e2 = Entry(master) 
e1.grid(row=0, column=1) 
e2.grid(row=1, column=1) 
redbutton = Button(frame, text = 'submit', fg ='red') 
redbutton.pack( side = LEFT) 
greenbutton = Button(frame, text = 'Brown', fg='brown') 
greenbutton.pack( side = LEFT ) 
bluebutton = Button(frame, text ='Blue', fg ='blue') 
bluebutton.pack( side = LEFT ) 
bottomframe = Frame(root) 
bottomframe.pack( side = BOTTOM ) 
blackbutton = Button(bottomframe, text ='Black', fg ='black') 
blackbutton.pack( side = BOTTOM)
w = Label(root, text='GeeksForGeeks.org!') 
w.pack() 
mainloop()
